apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
    - default:
        memory: 512M
        cpu: "0.1"
      defaultRequest:
        memory: 256M
        cpu: "0.01"
      type: Container