apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-linux-deployment
  namespace: sample-app
  labels:
    app: sample-linux-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-linux-app
  template:
    metadata:
      labels:
        app: sample-linux-app
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux