apiVersion: v1
kind: Service
metadata:
  name: sample-linux-service
  namespace: sample-app
  labels:
    app: sample-linux-app
spec:
  selector:
    app: sample-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80