--- 
# Ex:1
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "create","delete"]
--- 
# Ex:2
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2025-05-28T00:54:36Z"
  name: developer
  namespace: blue
  resourceVersion: "2674"
  uid: 3dee7882-01a2-4428-b227-8ccb59089fd0
rules:
- apiGroups:
  - ""
  resourceNames:
  - blue-app
  - dark-blue-app
  resources:
  - pods
  verbs:
  - get
  - watch
  - create
  - delete
---
# Ex:3
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2025-05-28T00:54:36Z"
  name: developer
  namespace: blue
  resourceVersion: "3319"
  uid: 3dee7882-01a2-4428-b227-8ccb59089fd0
rules:
- apiGroups:
  - ""
  resourceNames:
  - blue-app
  - dark-blue-app
  resources:
  - pods
  verbs:
  - get
  - watch
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create